//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_AutoFill
    {
        public int IDAutoFill { get; set; }
        public string AutoFillName { get; set; }
        public int IDDocumentType { get; set; }
        public int IDExternalDataBase { get; set; }
        public int IDExternalTable { get; set; }
        public int IDField { get; set; }
        public int IDExternalField { get; set; }
    
        public virtual AG_DocumentTypes AG_DocumentTypes { get; set; }
        public virtual AG_Fields AG_Fields { get; set; }
    }
}
