//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_Combos
    {
        public int IDCombo { get; set; }
        public int IDField { get; set; }
        public string ComboValue { get; set; }
    
        public virtual AG_Fields AG_Fields { get; set; }
        public virtual AG_Fields AG_Fields1 { get; set; }
    }
}
