//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_DocumentTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AG_DocumentTypes()
        {
            this.AG_AutoFill = new HashSet<AG_AutoFill>();
            this.AG_Groups = new HashSet<AG_Groups>();
            this.AG_Fields = new HashSet<AG_Fields>();
            this.AG_Groups1 = new HashSet<AG_Groups>();
            this.AG_Lots = new HashSet<AG_Lots>();
        }
    
        public int IDDocumentType { get; set; }
        public string DocumentName { get; set; }
        public string IndexTable { get; set; }
        public string ExportTable { get; set; }
        public int DocumentIndexType { get; set; }
        public bool AllowSignDocument { get; set; }
        public string FileTemplateForSectors { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_AutoFill> AG_AutoFill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Groups> AG_Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Fields> AG_Fields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Groups> AG_Groups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Lots> AG_Lots { get; set; }
    }
}
