//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_Fields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AG_Fields()
        {
            this.AG_AutoFill = new HashSet<AG_AutoFill>();
            this.AG_Combos = new HashSet<AG_Combos>();
            this.AG_Combos1 = new HashSet<AG_Combos>();
        }
    
        public int IDField { get; set; }
        public int IDDocumentType { get; set; }
        public int IDFieldType { get; set; }
        public string FieldName { get; set; }
        public int MaxValue { get; set; }
        public int MinValue { get; set; }
        public bool IsNuleable { get; set; }
        public bool IsUnique { get; set; }
        public bool IsLookup { get; set; }
        public bool IsEncrypted { get; set; }
        public Nullable<int> Posx1 { get; set; }
        public Nullable<int> Posy1 { get; set; }
        public Nullable<int> Posx2 { get; set; }
        public Nullable<int> Posy2 { get; set; }
        public Nullable<int> PageNum { get; set; }
        public Nullable<bool> IsSector { get; set; }
        public Nullable<int> IDVisualization { get; set; }
        public Nullable<bool> IsTextDeployable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_AutoFill> AG_AutoFill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Combos> AG_Combos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Combos> AG_Combos1 { get; set; }
        public virtual AG_DocumentTypes AG_DocumentTypes { get; set; }
        public virtual AG_FieldTypes AG_FieldTypes { get; set; }
    }
}
