//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AG_Groups()
        {
            this.AG_UserGroups = new HashSet<AG_UserGroups>();
            this.AG_UserGroups1 = new HashSet<AG_UserGroups>();
        }
    
        public int IDGroup { get; set; }
        public string GroupName { get; set; }
        public bool IndexPermission { get; set; }
        public bool AuditPermission { get; set; }
        public bool ImportLotsPermission { get; set; }
        public bool ExportLotsPermission { get; set; }
        public bool CreateDocumentsPermission { get; set; }
        public bool DeleteDocumentsPermission { get; set; }
        public bool EditDocumentsPermission { get; set; }
        public bool CreateGroupPermission { get; set; }
        public bool DeleteGroupPermission { get; set; }
        public bool ModifyGroupPermission { get; set; }
        public bool CreateUserPermission { get; set; }
        public bool DeleteUsersPermission { get; set; }
        public bool ModifyUsersPermission { get; set; }
        public bool PrintDocumentsPermission { get; set; }
        public bool EmailDocumentsPermission { get; set; }
        public bool ExportDocumentsPermission { get; set; }
        public bool CutPasteDocumentsPermission { get; set; }
        public bool DocumentNotesPermission { get; set; }
        public bool EditDocumentsDataPermission { get; set; }
        public bool ConfigurePermission { get; set; }
        public Nullable<int> IDDocumentType { get; set; }
        public Nullable<byte> DownloadDocumentPermission { get; set; }
        public Nullable<byte> EditNotesPermission { get; set; }
        public Nullable<byte> ViewNotesPermission { get; set; }
    
        public virtual AG_DocumentTypes AG_DocumentTypes { get; set; }
        public virtual AG_DocumentTypes AG_DocumentTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_UserGroups> AG_UserGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_UserGroups> AG_UserGroups1 { get; set; }
    }
}
