//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_LogUserAction
    {
        public int idLogUserAction { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> IDDocumentType { get; set; }
        public string IdsExport { get; set; }
    }
}
