//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_Lots
    {
        public int IDLot { get; set; }
        public string LotName { get; set; }
        public string LotOrigPath { get; set; }
        public System.DateTime LotCreationDate { get; set; }
        public bool IsLotClose { get; set; }
        public Nullable<int> LotTotalPages { get; set; }
        public string LotDestPath { get; set; }
        public Nullable<int> IDDocumentType { get; set; }
        public int Id_State { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> LotState { get; set; }
        public string LotDescPath { get; set; }
        public Nullable<int> LotIndexType { get; set; }
    
        public virtual AG_DocumentTypes AG_DocumentTypes { get; set; }
        public virtual AG_Users AG_Users { get; set; }
    }
}
