//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_LogUsers
    {
        public int IDLogRegister { get; set; }
        public Nullable<int> IDUser { get; set; }
        public System.DateTime Login { get; set; }
        public System.DateTime Logout { get; set; }
        public Nullable<long> Permanence { get; set; }
    
        public virtual AG_Users AG_Users { get; set; }
    }
}
