//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AG_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AG_Users()
        {
            this.AG_LogUsers = new HashSet<AG_LogUsers>();
            this.AG_Lots = new HashSet<AG_Lots>();
            this.AG_Query = new HashSet<AG_Query>();
            this.AG_Query1 = new HashSet<AG_Query>();
            this.AG_UserGroups = new HashSet<AG_UserGroups>();
        }
    
        public int IDUser { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsEnabled { get; set; }
        public string UserDescription { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IdConfigSearch { get; set; }
        public Nullable<byte> logueado { get; set; }
        public Nullable<System.DateTime> ult_ingreso { get; set; }
        public Nullable<bool> ReceiveMail { get; set; }
        public string Mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_LogUsers> AG_LogUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Lots> AG_Lots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Query> AG_Query { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_Query> AG_Query1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AG_UserGroups> AG_UserGroups { get; set; }
    }
}
