//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplika.Consulting.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_IndexingMDPEntities1 : DbContext
    {
        public DB_IndexingMDPEntities1()
            : base("name=DB_IndexingMDPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AG_AutoFill> AG_AutoFill { get; set; }
        public virtual DbSet<AG_Combos> AG_Combos { get; set; }
        public virtual DbSet<AG_DocumentTypes> AG_DocumentTypes { get; set; }
        public virtual DbSet<AG_Fields> AG_Fields { get; set; }
        public virtual DbSet<AG_FieldTypes> AG_FieldTypes { get; set; }
        public virtual DbSet<AG_Groups> AG_Groups { get; set; }
        public virtual DbSet<AG_LogUserAction> AG_LogUserAction { get; set; }
        public virtual DbSet<AG_LogUsers> AG_LogUsers { get; set; }
        public virtual DbSet<AG_Lots> AG_Lots { get; set; }
        public virtual DbSet<AG_Parametrics> AG_Parametrics { get; set; }
        public virtual DbSet<AG_Query> AG_Query { get; set; }
        public virtual DbSet<AG_UserGroups> AG_UserGroups { get; set; }
        public virtual DbSet<AG_Users> AG_Users { get; set; }
    }
}
